### ISSUE TITLE
Customize basemap layer in project view

### ISSUE THREAD

**Issue by planemad** [osm-in/osm-tasking-manager2#2]
Upstream: https://github.com/hotosm/osm-tasking-manager2/issues/682

**Comment by Andygol** [comment]
@planemad @batpad 
for now you can add custom imagery direct to code of TM like here https://github.com/osm-ua/osm-tasking-manager2/commit/d5badd59fcaa234d52e70f0f576c066ccc0830c1

**Comment by batpad** [comment]
@Andygol cool. Thanks. That may work as a quick fix if something desperately needed. I think the feature request would be to add a TileLayer as an attribute to a TM Project so that layers can be configured on a per-project basis.

Am muddling through the TM code - if this seems like something that is requested by more people in the community, I can work on creating a PR for submission.

**Comment by batpad** [comment]
Let's use the main repo. Closing here.
